/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as ReconciliationV1RouteImport } from './routes/reconciliation-v1'
import { Route as ContractsContractIdRouteImport } from './routes/contracts.$contractId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationV1Route = ReconciliationV1RouteImport.update({
  id: '/reconciliation-v1',
  path: '/reconciliation-v1',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsContractIdRoute = ContractsContractIdRouteImport.update({
  id: '/contracts/$contractId',
  path: '/contracts/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ledger': typeof LedgerRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reconciliation-v1': typeof ReconciliationV1Route
  '/contracts/$contractId': typeof ContractsContractIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ledger': typeof LedgerRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reconciliation-v1': typeof ReconciliationV1Route
  '/contracts/$contractId': typeof ContractsContractIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ledger': typeof LedgerRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reconciliation-v1': typeof ReconciliationV1Route
  '/contracts/$contractId': typeof ContractsContractIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ledger'
    | '/reconciliation'
    | '/reconciliation-v1'
    | '/contracts/$contractId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ledger'
    | '/reconciliation'
    | '/reconciliation-v1'
    | '/contracts/$contractId'
  id:
    | '__root__'
    | '/'
    | '/ledger'
    | '/reconciliation'
    | '/reconciliation-v1'
    | '/contracts/$contractId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LedgerRoute: typeof LedgerRoute
  ReconciliationRoute: typeof ReconciliationRoute
  ReconciliationV1Route: typeof ReconciliationV1Route
  ContractsContractIdRoute: typeof ContractsContractIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation-v1': {
      id: '/reconciliation-v1'
      path: '/reconciliation-v1'
      fullPath: '/reconciliation-v1'
      preLoaderRoute: typeof ReconciliationV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$contractId': {
      id: '/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof ContractsContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LedgerRoute: LedgerRoute,
  ReconciliationRoute: ReconciliationRoute,
  ReconciliationV1Route: ReconciliationV1Route,
  ContractsContractIdRoute: ContractsContractIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
