/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FuelWorkspaceRouteImport } from './routes/fuel-workspace'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as ReconciliationBoardRouteImport } from './routes/reconciliation-board'
import { Route as ReconciliationConceptsRouteImport } from './routes/reconciliation-concepts'
import { Route as ReconciliationEvidenceRouteImport } from './routes/reconciliation-evidence'
import { Route as ReconciliationMatrixRouteImport } from './routes/reconciliation-matrix'
import { Route as ReconciliationV1RouteImport } from './routes/reconciliation-v1'
import { Route as ContractsContractIdRouteImport } from './routes/contracts.$contractId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelWorkspaceRoute = FuelWorkspaceRouteImport.update({
  id: '/fuel-workspace',
  path: '/fuel-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationBoardRoute = ReconciliationBoardRouteImport.update({
  id: '/reconciliation-board',
  path: '/reconciliation-board',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationConceptsRoute = ReconciliationConceptsRouteImport.update({
  id: '/reconciliation-concepts',
  path: '/reconciliation-concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationEvidenceRoute = ReconciliationEvidenceRouteImport.update({
  id: '/reconciliation-evidence',
  path: '/reconciliation-evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationMatrixRoute = ReconciliationMatrixRouteImport.update({
  id: '/reconciliation-matrix',
  path: '/reconciliation-matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationV1Route = ReconciliationV1RouteImport.update({
  id: '/reconciliation-v1',
  path: '/reconciliation-v1',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsContractIdRoute = ContractsContractIdRouteImport.update({
  id: '/contracts/$contractId',
  path: '/contracts/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fuel-workspace': typeof FuelWorkspaceRoute
  '/ledger': typeof LedgerRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reconciliation-board': typeof ReconciliationBoardRoute
  '/reconciliation-concepts': typeof ReconciliationConceptsRoute
  '/reconciliation-evidence': typeof ReconciliationEvidenceRoute
  '/reconciliation-matrix': typeof ReconciliationMatrixRoute
  '/reconciliation-v1': typeof ReconciliationV1Route
  '/contracts/$contractId': typeof ContractsContractIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fuel-workspace': typeof FuelWorkspaceRoute
  '/ledger': typeof LedgerRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reconciliation-board': typeof ReconciliationBoardRoute
  '/reconciliation-concepts': typeof ReconciliationConceptsRoute
  '/reconciliation-evidence': typeof ReconciliationEvidenceRoute
  '/reconciliation-matrix': typeof ReconciliationMatrixRoute
  '/reconciliation-v1': typeof ReconciliationV1Route
  '/contracts/$contractId': typeof ContractsContractIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fuel-workspace': typeof FuelWorkspaceRoute
  '/ledger': typeof LedgerRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reconciliation-board': typeof ReconciliationBoardRoute
  '/reconciliation-concepts': typeof ReconciliationConceptsRoute
  '/reconciliation-evidence': typeof ReconciliationEvidenceRoute
  '/reconciliation-matrix': typeof ReconciliationMatrixRoute
  '/reconciliation-v1': typeof ReconciliationV1Route
  '/contracts/$contractId': typeof ContractsContractIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fuel-workspace'
    | '/ledger'
    | '/reconciliation'
    | '/reconciliation-board'
    | '/reconciliation-concepts'
    | '/reconciliation-evidence'
    | '/reconciliation-matrix'
    | '/reconciliation-v1'
    | '/contracts/$contractId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fuel-workspace'
    | '/ledger'
    | '/reconciliation'
    | '/reconciliation-board'
    | '/reconciliation-concepts'
    | '/reconciliation-evidence'
    | '/reconciliation-matrix'
    | '/reconciliation-v1'
    | '/contracts/$contractId'
  id:
    | '__root__'
    | '/'
    | '/fuel-workspace'
    | '/ledger'
    | '/reconciliation'
    | '/reconciliation-board'
    | '/reconciliation-concepts'
    | '/reconciliation-evidence'
    | '/reconciliation-matrix'
    | '/reconciliation-v1'
    | '/contracts/$contractId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FuelWorkspaceRoute: typeof FuelWorkspaceRoute
  LedgerRoute: typeof LedgerRoute
  ReconciliationRoute: typeof ReconciliationRoute
  ReconciliationBoardRoute: typeof ReconciliationBoardRoute
  ReconciliationConceptsRoute: typeof ReconciliationConceptsRoute
  ReconciliationEvidenceRoute: typeof ReconciliationEvidenceRoute
  ReconciliationMatrixRoute: typeof ReconciliationMatrixRoute
  ReconciliationV1Route: typeof ReconciliationV1Route
  ContractsContractIdRoute: typeof ContractsContractIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel-workspace': {
      id: '/fuel-workspace'
      path: '/fuel-workspace'
      fullPath: '/fuel-workspace'
      preLoaderRoute: typeof FuelWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation-board': {
      id: '/reconciliation-board'
      path: '/reconciliation-board'
      fullPath: '/reconciliation-board'
      preLoaderRoute: typeof ReconciliationBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation-concepts': {
      id: '/reconciliation-concepts'
      path: '/reconciliation-concepts'
      fullPath: '/reconciliation-concepts'
      preLoaderRoute: typeof ReconciliationConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation-evidence': {
      id: '/reconciliation-evidence'
      path: '/reconciliation-evidence'
      fullPath: '/reconciliation-evidence'
      preLoaderRoute: typeof ReconciliationEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation-matrix': {
      id: '/reconciliation-matrix'
      path: '/reconciliation-matrix'
      fullPath: '/reconciliation-matrix'
      preLoaderRoute: typeof ReconciliationMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation-v1': {
      id: '/reconciliation-v1'
      path: '/reconciliation-v1'
      fullPath: '/reconciliation-v1'
      preLoaderRoute: typeof ReconciliationV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$contractId': {
      id: '/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof ContractsContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FuelWorkspaceRoute: FuelWorkspaceRoute,
  LedgerRoute: LedgerRoute,
  ReconciliationRoute: ReconciliationRoute,
  ReconciliationBoardRoute: ReconciliationBoardRoute,
  ReconciliationConceptsRoute: ReconciliationConceptsRoute,
  ReconciliationEvidenceRoute: ReconciliationEvidenceRoute,
  ReconciliationMatrixRoute: ReconciliationMatrixRoute,
  ReconciliationV1Route: ReconciliationV1Route,
  ContractsContractIdRoute: ContractsContractIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
